export const apis = {
  products: 'products?filter=&sort=',
  testimonials: 'testimonials',
  team: 'employees',
  support: 'services',
  categories: 'categories',
  login: 'login',
  register: 'register',
  contact: 'messages',
  cart: 'cart',
  deleteFromCart: 'cart/deleteProduct',
  order: 'order',
  users: 'users',
  productsAdmin: 'admin/products',
}
